### ISSUE TITLE
Add indicator/label when device is disconnected

### ISSUE THREAD

**Issue by oparada1988** [StreamController/Battery#1]
Add an indicator for when a device is disconnected, in my example my xbox bluetooth controller is disconnected but the plugin just shows a "?"

![rn_image_picker_lib_temp_11f031bb-4c90-4fbd-adf6-8a8a4ed6faf3](https://github.com/StreamController/Battery/assets/4031078/f8eeab89-1f95-476e-9307-e34bc545d2c4)

**Comment by Core447** [comment]
Implemented with 09db0e3b90895c1f4f8dd22d47fc18563b411d62
